- id: fmt
  name: fmt
  description: Format files with cargo fmt.
  entry: cargo fmt
  language: rust
  types: [rust]
  args: ["--"]
  pass_filenames: false
- id: cargo-check
  name: cargo check
  description: Check the package for errors.
  entry: cargo check
  language: rust
  types: [rust]
  pass_filenames: false
- id: cargo-test
  name: cargo test
  description: Run tests
  entry: cargo test
  language: system
  types: [rust]
  pass_filenames: false
- id: clippy
  name: clippy
  description: Lint rust sources
  entry: cargo clippy
  language: rust
  args: ["--", "-D", "warnings"]
  types: [rust]
  pass_filenames: false
- id: update
  name: update
  description: updates cargo packages and lock file
  entry: cargo update
  language: system
  types: [rust]
  pass_filenames: false

